import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@aulara/ui/globals.css";
import type { PropsWithChildren } from "react";

const geistSans = Geist({
	variable: "--font-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
	variable: "--font-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
		<body className="relative">
			<div className="isolate relative flex min-h-svh flex-col">{children}</div>
		</body>
    </html>
  );
}
